### PR TITLE
138 fix signuters and types in store package

### LINKED ISSUE #138: fix signuters and types in store package

### PR DESCRIPTION
**Pull request by idonag**

### CODE REVIEW

File: Market-Trading-System/src/main/java/DomainLayer/Market/Store/IStoreFacade.java [hunk 1]
```diff
@@ -17,9 +17,9 @@ public static IStoreFacade getInstance(IRepository<Long, Store> storesRepo)
     }
     public void setUserFacade(IUserFacade userFacade);
     public void setPurchaseFacade(IPurchaseFacade purchaseFacadeInstance);
-    public void createStore(String founderId, String storeName, String storeDescription, IRepository<Long, Discount> discounts)throws Exception;
+    public long createStore(String founderId, String storeName, String storeDescription, IRepository<Long, Discount> discounts)throws Exception;
```
Comment (idonag) [inline Market-Trading-System/src/main/java/DomainLayer/Market/Store/IStoreFacade.java:20]: test purposes

**Review by noamgilad98 — APPROVED** [review]
